### ISSUE TITLE
Double opt-in

### ISSUE THREAD

**Issue by Justinomics** [cultuurnet/mailjet-subscribe#1]
Great work! Any plans to enable support for double opt-in in the future? E.g. https://www.mailjet.com/blog/news/how-to-set-up-a-double-opt-via-mailjets-api/

**Comment by janhenckens** [comment]
Hey @justinpyvis - We're using this in a specific project, where we're not using Mailjet's double opt-in so no plans to add it for now. Open to a PR to add it though, and happy to review/finish it :)
